name: learn-github-actions
on: [push]
jobs:
  check-bats-versions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is a pen"
      - uses: actions/checkout@v2
      - run: |
          ls -la
          cd .github/workflows/
          ls -la